"""add report_calculated

Revision ID: 40471f012a37
Revises: 96addd0d7d92
Create Date: 2025-03-29 18:30:11.461208

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40471f012a37'
down_revision = '96addd0d7d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'report_calculated',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('report_id', sa.UUID(), nullable=True),
        sa.Column('effective_pressure', sa.Float(), nullable=True),
        sa.Column('required_charges', sa.Integer(), nullable=True),
        sa.Column('gas_volume', sa.Float(), nullable=True),
        sa.Column('impact_duration', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['report_id'],
            ['reports.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('report_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_calculated')
    # ### end Alembic commands ###
