"""add is_admin to users

Revision ID: 4afcf5ee50b3
Revises: db9bfef506d5
Create Date: 2025-03-29 17:36:58.637246

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afcf5ee50b3'
down_revision = 'db9bfef506d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
