"""add is_admin to users

Revision ID: 96addd0d7d92
Revises: 4afcf5ee50b3
Create Date: 2025-03-29 17:40:01.051161

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96addd0d7d92'
down_revision = '4afcf5ee50b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
