"""initial

Revision ID: db9bfef506d5
Revises:
Create Date: 2025-03-25 21:26:47.221869

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9bfef506d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'locations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
    )
    op.create_table(
        'clusters',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('location_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['location_id'],
            ['locations.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'wells',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('cluster_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cluster_id'],
            ['clusters.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'well_states',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('well_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=True),
        sa.Column('depth', sa.Float(), nullable=True),
        sa.Column('pressure', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['well_id'],
            ['wells.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'reports',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('well_state_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['well_state_id'],
            ['well_states.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_report_permissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('report_id', sa.UUID(), nullable=False),
        sa.Column('is_owner', sa.Boolean(), nullable=True),
        sa.Column('can_edit', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ['report_id'],
            ['reports.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_report_permissions')
    op.drop_table('reports')
    op.drop_table('well_states')
    op.drop_table('wells')
    op.drop_table('clusters')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
